function getCommentary(ballOutcome) {
  const commentary = {
    0: [
      "Tightly bowled, no run. The batter defends solidly.",
      "A play and a miss! The ball whizzes past the edge.",
      "Straight to the fielder, a comfortable dot ball.",
      "The batter leaves it! Good length from the bowler.",
      "Stifled! The bowler cramps the batter for room.",
      "Maiden over material! Another dot ball.",
      "Patient bowling, rewarded with a dot.",
      "The ball dies on its way to the keeper.",
      "Solid defense shown by the batter.",
      "No run. The pressure builds.",
    ],
    1: [
      "A quick single, well run.",
      "Tapped into the gap for a single.",
      "Easy single, strike rotated.",
      "A nudge and a run taken.",
      "Just a single, but it's important.",
      "The batters exchange a single.",
      "Into the off-side for one.",
      "A single to keep the scoreboard ticking.",
      "Run taken, fielder closes in.",
      "A single, good running.",
    ],
    2: [
      "Driven into the gap, two runs.",
      "Well-placed shot, two runs taken.",
      "Good running, two runs added.",
      "The batters push hard, two runs.",
      "Two runs, the fielder chases.",
      "Driven firmly, a couple of runs.",
      "Two runs, good placement.",
      "A comfortable two runs.",
      "The batters scamper through for two.",
      "Flicked away, two runs.",
    ],
    3: [
      "Driven to the deep, three runs.",
      "Good running, three runs taken.",
      "Three runs, the fielders work hard.",
      "A well-run three runs.",
      "Three runs, into the outfield.",
      "Driven powerfully, three runs.",
      "A quick three runs.",
      "The batters push for three.",
      "Three runs, a good effort.",
      "A well-placed drive, three runs.",
    ],
    4: [
      "CRACK! Four runs! What a shot!",
      "FOUR! The ball races to the boundary!",
      "Boundary! Four runs for the batter!",
      "Driven powerfully, FOUR runs!",
      "A classic four! The fielder had no chance.",
      "Glorious shot! Four runs!",
      "FOUR! The crowd roars!",
      "Perfect timing, FOUR runs!",
      "A boundary! Four runs added.",
      "Elegant shot, FOUR runs!",
    ],
    5: [
      "CAUGHT! And that's the end of the innings.",
      "OUT! A brilliant catch in the outfield.",
      "Caught behind! The keeper takes it.",
      "A sharp catch! The batter departs.",
      "Taken! The fielder makes no mistake.",
      "Caught! And the batter is out.",
      "A good catch! The batter walks.",
      "Caught in the slips! Out!",
      "A diving catch! What a moment!",
      "Caught! The bowler celebrates.",
    ],
    6: [
      "SIX! And it's out of the park!",
      "SIX runs! A massive hit!",
      "Out of here! SIX runs!",
      "A towering SIX! Into the stands!",
      "SIX! The crowd goes wild!",
      "Maximum! SIX runs!",
      "What a hit! SIX runs!",
      "A huge SIX! Over the boundary!",
      "SIX! The ball sails away!",
      "An enormous SIX!",
    ],
    11: [
      "WIDE! That's an extra run.",
      "The umpire signals WIDE.",
      "WIDE ball, extra conceded.",
      "A WIDE delivery, another run.",
      "WIDE! The batter gets a freebie.",
      "Too wide, and it's a WIDE.",
      "WIDE! The bowler misses the line.",
      "WIDE! The batter will take that.",
      "WIDE! The extra run is added.",
      "WIDE! The bowler has to reload.",
    ],
    7: [
      "LBW! And the batter is out.",
      "OUT! LBW decision.",
      "LBW! No doubt about that one.",
      "The batter is trapped LBW!",
      "OUT! LBW, the finger goes up.",
      "LBW! And the batter has to go.",
      "Plumb LBW! OUT!",
      "LBW! The batter is dismissed.",
      "OUT! LBW, a clear decision.",
      "LBW! The bowler celebrates!",
    ],
    8: [
      "BOWLED! The stumps are shattered.",
      "OUT! Bowled him!",
      "Bowled! The batter has no answer.",
      "Clean BOWLED! What a delivery!",
      "Bowled! The stumps are flying.",
      "OUT! Bowled, a perfect ball.",
      "Bowled! The batter is dismissed.",
      "Bowled! The timber is struck.",
      "OUT! Bowled, a great delivery.",
      "Bowled! The batter is stunned.",
    ],
    10: [
      "RUN OUT! And the batter is stranded.",
      "OUT! Run out, a direct hit!",
      "Run out! The fielder does well.",
      "A RUN OUT! The batter is short.",
      "OUT! Run out, a mix-up.",
      "Run out! The throw is accurate.",
      "OUT! Run out, the batter is gone.",
      "Run out! The fielding is sharp.",
      "OUT! Run out, a brilliant effort.",
      "Run out! The batter is dismissed.",
    ],
    12: [
      "NO BALL! Free hit coming up.",
      "It's a NO BALL! Extra run.",
      "NO BALL! The bowler oversteps.",
      "A NO BALL! And a free hit.",
      "NO BALL! The batter gets a chance.",
      "NO BALL! Extra run added.",
      "It's a NO BALL! Free hit.",
      "NO BALL! The bowler erred.",
      "A NO BALL! Run and a free hit.",
      "NO BALL! The batter survives.",
    ],
    9: [
      "STUMPED! The batter is out of his crease.",
      "OUT! Stumped by the keeper.",
      "Stumped! The batter is dismissed.",
      "A sharp stumping! OUT!",
      "Stumped! The keeper does well.",
      "OUT! Stumped, a quick take.",
      "Stumped! The batter is gone.",
      "OUT! Stumped, a brilliant play.",
      "Stumped! The batter is out.",
      "OUT! Stumped, the bails are off.",
    ],
    13: [
      "LEG BYES! A single taken.",
      "Run taken as LEG BYES.",
      "LEG BYES, one run.",
      "A single off LEG BYES.",
      "Run taken off LEG BYES.",
      "One run, LEG BYES.",
      "Single off LEG BYES.",
      "LEG BYES, a single.",
      "Run off LEG BYES.",
      "A single, LEG BYES.",
    ],
    14: [
      "BYES! A run taken.",
      "Run taken as BYES.",
      "BYES, one run.",
      "A single off BYES.",
      "Run taken off BYES.",
      "One run, BYES.",
      "Single off BYES.",
      "BYES, a single.",
      "Run off BYES.",
      "A single, BYES.",
    ],
  };
  const commentaryArray = commentary[ballOutcome];
  return commentaryArray[Math.floor(Math.random() * commentaryArray.length)];
}
export default getCommentary;