function getCommentary(ballOutcome) {
  const commentary = {
    0: [
      "The bowler’s precision has tied the batsman down—dot ball and pressure mounting!",
      "It's another dot ball! The fielders are right where they need to be.",
      "Beautifully bowled—no room for the batsman to score here!",
      "The batsman steps forward but finds the fielder in his way—dot ball!",
      "That’s tight bowling; the batsman couldn't get it past the infield!",
      "Dot ball again! The bowler is weaving his magic.",
      "Every dot ball counts—it’s all about building pressure in this phase!",
      "A defensive stroke from the batsman—no run, dot ball!",
      "The bowler keeps it on a good length; the batsman plays it straight back.",
      "What a spell—another dot! The fielding side is holding firm."
    ],
    1: [
      "Nicely placed into the gap for a quick single!",
      "A well-judged run—great communication between the batsmen.",
      "Soft hands and a gentle push for a comfortable single.",
      "Quick on his feet, the batsman sneaks a run with ease.",
      "A single taken with a deft touch into the off-side.",
      "Good running between the wickets to rotate the strike.",
      "The batsman nudges it behind square for a quick single.",
      "Great awareness as the batsman pinches a run!",
      "A confident push into the infield to collect a single.",
      "A smart single to keep the scoreboard ticking over."
    ],
    2: [
      "The batsmen sprint back for two—excellent running between the wickets!",
      "A firm push into the gap and they manage to steal a couple.",
      "Great placement! The fielders chase hard, but it’s an easy two.",
      "The batsmen turn quickly and complete two runs with ease.",
      "Nicely timed shot—it doesn’t reach the boundary, but they run two.",
      "Fantastic running! They’ve converted what looked like a single into a double.",
      "A smart flick off the pads, and they come back for the second run.",
      "Good awareness from the batsmen as they capitalize on the gap for two.",
      "They run the first one hard and get back comfortably for the second.",
      "Quick feet and sharp calling ensure two well-earned runs."
    ],
    3: [
      "Excellent placement! The ball races past the fielder, and they run three.",
      "Quick running and sharp calling turn this into three well-earned runs!",
      "A clever push into the deep, and they sprint back for three runs!",
      "The batsmen take advantage of the gap and come back for a third run—great hustle!",
      "Great timing but no boundary; instead, they’ve managed to collect three.",
      "They run hard between the wickets to convert this into three runs!",
      "Precision placement allows them to sneak in three runs comfortably.",
      "Aggressive running ensures they grab three runs from that shot!",
      "The batsmen's awareness and speed earn them three valuable runs.",
      "Good teamwork! They’ve covered a lot of ground to secure three runs."
    ],
    4: [
      "Cracking shot! The ball races to the boundary for four runs.",
      "Superb timing—it's a four! The fielder had no chance.",
      "Elegant stroke from the batsman, and it’s four runs all the way!",
      "The batsman drives it beautifully, piercing the gap for a boundary!",
      "A thunderous hit—straight to the ropes! Four runs!",
      "What a glorious shot! The ball speeds across the grass for four.",
      "The batsman finds the gap with precision—four valuable runs!",
      "No stopping that one—it's four more to the tally!",
      "Fantastic execution; the ball kisses the boundary line for four!",
      "That’s class! A picture-perfect shot resulting in four runs."
    ],
    6: [
      "What a colossal strike! The ball sails over the boundary for six!",
      "Up, up, and away—it’s a six! A stunning hit by the batsman.",
      "That’s out of the park! The batsman unleashes a massive six!",
      "Sheer power and timing—the ball disappears into the stands for six!",
      "Boom! That’s six runs in style—what a brilliant shot!",
      "High and handsome! The batsman smashes it all the way for six!",
      "It's a maximum! The bowler can only watch as it soars over the ropes.",
      "The batsman sends it to the moon and back—six runs on the board!",
      "The crowd erupts as the batsman launches a thunderous six!",
      "An effortless flick, and the ball sails over the fielders for six!"
    ],
    5: [
      "He's gone! A brilliant catch in the deep, and the batsman has to walk back.",
      "What a grab! The fielder makes no mistake, and that's the end of the innings.",
      "Caught! The batsman tried to go big but found the fielder instead.",
      "A sharp catch at slip, and the bowler gets his reward!",
      "The batsman miscues the shot, and it's safely pouched by the fielder.",
      "Up in the air... and taken! The batsman departs after a mistimed shot.",
      "An excellent diving catch seals the batsman's fate!",
      "The fielder judges it perfectly under pressure—caught and out!",
      "A simple catch in the outfield, and the batsman is dismissed.",
      "The bowler celebrates as the fielder completes a stunning catch!"
    ],
    7: [
      "The umpire raises his finger—out LBW! The batsman is trapped in front.",
      "That’s plumb! The ball hits the pads, and the batsman is given out LBW.",
      "A loud appeal, and the umpire agrees—LBW! The batsman has to go.",
      "No doubt about that one—straight in line, and the batsman is out LBW.",
      "The bowler gets his reward as the batsman is caught leg before wicket!",
      "The batsman misjudges the line, and the umpire signals LBW!",
      "A perfect delivery—hits the pads, and the batsman is out LBW!",
      "The fielding side erupts in celebration as the umpire gives LBW!",
      "The batsman fails to offer a shot, and the umpire rules LBW!",
      "A brilliant appeal, and the umpire confirms—LBW! The bowler strikes again."
    ],
    8: [
      "Clean bowled! The stumps are shattered, and the batsman is out!",
      "What a delivery! The ball sneaks through and rattles the stumps.",
      "The bowler strikes—straight through the defenses and bowled!",
      "An absolute peach of a delivery, and the batsman is bowled!",
      "The batsman misjudges the line, and the stumps are sent flying!",
      "Bowled him! The bowler celebrates as the batsman walks back.",
      "The ball crashes into the stumps—bowled! A fantastic wicket.",
      "Through the gate and onto the stumps—what a brilliant delivery!",
      "The batsman is beaten all ends up, and the bowler gets his reward!",
      "The stumps are uprooted! A perfect delivery to dismiss the batsman."
    ],
    9: [
      "Quick as lightning! The keeper whips off the bails, and the batsman is stumped!",
      "Brilliant work behind the stumps—caught the batsman out of his crease!",
      "The batsman steps out, misses the ball, and the keeper does the rest—stumped!",
      "What a sharp piece of glovework! The batsman is stumped in a flash.",
      "The bowler lures the batsman forward, and the keeper finishes the job—stumped!",
      "A moment of magic from the wicketkeeper—stumps shattered, batsman out!",
      "The batsman dances down the track but is left stranded—stumped!",
      "The keeper’s reflexes are on point—bails off, and the batsman is gone!",
      "A clever delivery deceives the batsman, and the keeper pounces—stumped!",
      "The batsman takes a chance, but the keeper is too quick—stumped out!"
    ],
    10: [
      "What a direct hit! The batsman is caught short of his crease—run out!",
      "Brilliant fielding! A sharp throw and the batsman is run out.",
      "The fielder's quick reflexes result in a stunning run-out!",
      "A mix-up between the batsmen, and the fielding side capitalizes—run out!",
      "The throw is right on target, and the batsman is well short—run out!",
      "Superb awareness from the fielder to execute a perfect run-out!",
      "The batsmen hesitate, and the fielder makes them pay—run out!",
      "A rocket throw from the deep, and the keeper does the rest—run out!",
      "The batsman takes a risky single, but the fielder is too quick—run out!",
      "A game-changing moment as the batsman is run out by a whisker!"
    ],
    11: [
      "That's a wide! The bowler loses his line, and the umpire stretches his arms.",
      "Wayward delivery—called wide by the umpire, and the batting side gets an extra run.",
      "The bowler strays too far outside the off-stump, and it's signaled wide!",
      "A loose ball down the leg side—wide called by the umpire.",
      "The bowler will have to reload that one—it's a wide delivery.",
      "Too much width offered, and the umpire has no hesitation in calling it wide.",
      "The batsman lets it go, and the umpire signals a wide ball.",
      "A rare mistake from the bowler as he concedes a wide.",
      "The bowler misses his mark, and the batting side gets a bonus run—wide ball!",
      "An erratic delivery, and the umpire stretches his arms for a wide."
    ],
    12: [
      "That's a no-ball! The bowler oversteps, and the batting side gets a free hit.",
      "A costly mistake by the bowler—no-ball signaled by the umpire!",
      "The bowler loses his footing, and it's called a no-ball.",
      "A rare error from the bowler—no-ball, and the batsman gets another chance.",
      "The umpire stretches his arm—it's a no-ball, and the pressure is on the bowler.",
      "A high full toss, and the umpire calls it a no-ball for height.",
      "The bowler has overstepped, and the batting side gets an extra run—no-ball!",
      "A no-ball gives the batsman a free hit—can they capitalize on it?",
      "The bowler's front foot crosses the line, and it's a no-ball!",
      "A crucial error at this stage—no-ball, and the batting side gets a bonus."
    ],
    13: [
      "The ball brushes the pads, and they sneak a quick single—leg byes signaled!",
      "A gentle deflection off the batsman’s body, and they take a single—leg byes!",
      "Smart running as the batsmen capitalize on the deflection for a single—leg byes.",
      "The ball clips the batsman’s leg, and they manage to steal a single—leg byes awarded.",
      "Quick thinking from the batsmen as they grab a single off the pads—leg byes!",
      "The umpire pats his knee, signaling leg byes as the batsmen complete a single.",
      "A slight ricochet off the batsman’s body, and they run a single—leg byes!",
      "The ball strays onto the pads, and the batsmen take a sharp single—leg byes signaled.",
      "Good awareness from the batsmen as they pick up a single through leg byes.",
      "The ball deflects off the batsman, and they scamper through for a single—leg byes!"
    ],
    14: [
      "The ball slips past the keeper, and the batsmen sneak a single—byes signaled!",
      "A misjudgment behind the stumps allows the batsmen to take a single—byes!",
      "The ball races away after missing the keeper, and the batsmen grab a single—byes awarded.",
      "Quick running as the batsmen capitalize on the keeper's miss for a single—byes!",
      "The ball evades the keeper, and the batsmen scamper through for a single—byes signaled.",
      "A slight misfield behind the stumps, and the batsmen take a single—byes!",
      "The keeper fails to gather cleanly, and the batsmen steal a single—byes!",
      "The ball trickles away after missing the keeper, and the batsmen complete a single—byes!",
      "Good awareness from the batsmen as they pick up a single through byes.",
      "The ball sneaks past the keeper, and the batsmen take advantage for a single—byes!"
    ],
    15: [
      "Dot ball on a free hit! No runs scored, the bowler holds their nerve, and the batter misses an opportunity—great pressure play!",
      "Capitalizing on the free hit, the batter skillfully earns a single run, keeping the momentum alive.",
      "Making the most of the free hit, the batter smartly runs between the wickets to secure 2 valuable runs, adding to the team's tally.",
      "Displaying excellent running between the wickets, the batter maximizes the free hit by securing 3 impressive runs.",
      "With precision and power, the batter smashes the free hit to the boundary for a fantastic 4 runs.",
      "What a colossal strike! The ball sails over the boundary for six!",
      "He's gone! A brilliant catch in the deep, and the batsman has to walk back.",
      "That’s plumb! The ball hits the pads, and the batsman is given out LBW.",
      "Bowled on a free hit! The stumps are down, but the batter stays—drama unfolds as the game goes on!",
      "LBW on a free hit! The appeal goes up, but the batter stays—an unusual twist in the game’s drama!",
      "Caught on a free hit! The fielder takes it, but the batter is safe—what a rare moment in cricket!",
      "Run out on a free hit! The batter gambled for the run but fell short—dismissal is certain, and the fielding side celebrates!",
      "Dot ball on a free hit! No runs scored, the bowler holds their nerve, and the batter misses an opportunity—great pressure play!",
      "Through the gate and onto the stumps—what a brilliant delivery!",
      "Quick as lightning! The keeper whips off the bails, and the batsman is stumped!",
      "Six runs on a free hit! The batter seizes the opportunity, sending the ball soaring into the stands—what a stunning strike under pressure!",
      "Four runs on a free hit! The batter pierces the field with precision, sending the ball racing to the boundary—an excellent display of skill!",
      "A quick single on the free hit! The batter keeps the scoreboard ticking with smart running.",
      "Two runs on the free hit! Excellent placement and good running between the wickets.",
      "Three runs on the free hit! Outstanding running and sharp awareness to capitalize on the opportunity.",
      "What a direct hit! The batsman is caught short of his crease—run out!"
    ]
  };
  const commentaryArray = commentary[ballOutcome];
  return commentaryArray[Math.floor(Math.random() * commentaryArray.length)];
}
export default getCommentary;